### PR TITLE
Introduce the 'usertemp' filesystem type

### PR DESCRIPTION
**Pull request by dscho**
In the context of Git for Windows, the MSys2 root lives inside
`%PROGRAMFILES%` which is typically write-protected for mere mortals' user
accounts. In particular for `/tmp/`, this is a problem, because many
scripts assume that writing to `/tmp/` is fair game.

MSys1 used to mount `/tmp/` automatically, pointing to the current user's
temporary directory.

Let's recreate that functionality in a slightly different way: we now
interpret the filesystem type "usertemp" in the `/etc/fstab` file. To make
`/tmp/` point to the temporary directory of the current user, as per the
`%TMP%` environment variable, just add this line to `/etc/fstab`:

```
	none /tmp usertemp binary,posix=0 0 0
```

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>

### CODE REVIEW

**Comment by Alexpux** [comment]
@dscho rebase all pulls to master please

**Comment by dscho** [comment]
Oh, sorry! Will do.

**Comment by dscho** [comment]
Actually, I assume you meant *`msys2-master`*, not *`master`*...

**Comment by dscho** [comment]
All my PRs updated.

**Comment by dscho** [comment]
I am actually considering to submit this patch directly to Cygwin. @Alexpux any objections?

**Comment by Alexpux** [comment]
@dscho, you can try to talk about this in Cygwin ML

**Comment by dscho** [comment]
Yes, that is what I wanted to do, but since I opened the Pull Request here, I did not want to step on your toes by "circumventing" you.

**Comment by dscho** [comment]
So you are okay with me submitting this to Cygwin, and letting this Pull Request lie dormant for a while?

**Comment by Alexpux** [comment]
I'm ok if it will be applied upstream in Cygwin. If it accepted we will get it automatically and close this pull request

**Comment by dscho** [comment]
Thanks for the confirmation!

**Comment by dscho** [comment]
This feature made it into Cygwin by now, and made it back into the MSys2 runtime.

**Pull request closed without merging**
