### PR TITLE
error: failed retrieving file 'msys.db' (Solved on x86_64 Windows 10)

### PR DESCRIPTION
**Pull request by originalsurfmex**
pacman.conf sets `Architecture = auto` and it appears that `auto` uses `uname -m` which results in `86_64`.
the msys mirror paths use `x86_64` not `86_64`
as a result I manually changed pacman.conf to say `Architecture = x86_64`. This might be useful if posted somewhere for others having similar problems.

This was one example from the debug result of pacman -Syuv --debug
`debug: response code: 404 error: failed retrieving file 'msys.db' from repo.msys2.org : The requested URL returned error: 404 debug: url: https://sourceforge.net/projects/msys2/files/REPOS/MSYS2/86_64/msys.db`
it should instead direct to:
`https://sourceforge.net/projects/msys2/files/REPOS/MSYS2/86_64/msys.db`

### CODE REVIEW

**Comment by dscho** [comment]
> `uname -m` which results in `86_64`

This looks like the bug I just fixed in Git for Windows' fork of the msys2-runtime: https://github.com/git-for-windows/msys2-runtime/commit/fcc3187b11b9d0e979a702503104cfaac8b5eab4

**Comment by dscho** [comment]
BTW it would be totally inappropriate to merge this PR, as it

1. targets `master` (which is a big no, no, as `master` tracks *Cygwin*'s `master`) instead of `msys2-master`
2. tries to merge Git for Windows' complete `master` branch, including many a merging-rebase, which is totally uncool for two reasons:
    1. the merging-rebases were never intended to be pushed into MSYS2's commit history
    2. it became pretty clear already early in the Git for Windows v2.x cycle that the way MSYS2 is run, and the way the Git for Windows is developed, are too incompatible to allow for a pleasant exchange of patches, read: Git for Windows' patches were rejected without much in the way of a clear message why, and how they would have to be improved.

**Comment by dscho** [comment]
@Alexpux if you read this, please:

1. close this PR
2. have a look at https://github.com/git-for-windows/msys2-runtime/commit/fcc3187b11b9d0e979a702503104cfaac8b5eab4 before you rebase `msys2-master` onto v3.0.1

**Comment by Alexpux** [comment]
@dscho I will look, but as I tell earlier on Gitter, I will leave MSYS2 project this year. I don’t want to be it maintainer anymore

**Comment by dscho** [comment]
> I tell earlier on Gitter

I am not in that channel, so I had no idea.

> I will leave MSYS2 project this year. I don’t want to be it maintainer anymore

Okay. Are there any takers so far?

**Comment by dscho** [comment]
@Alexpux would you terribly mind closing this bogus PR?

**Comment by originalsurfmex** [comment]
sure thing, sorry about the trouble and thanks for the hard work on this amazing project!

**Pull request closed without merging**
